### ISSUE TITLE
ERROR: Service 'frontend' failed to build: COPY failed

### ISSUE THREAD

**Issue by kREATUr67** [HDInnovations/UNIT3D-Community-Edition-Docker#1]
After starting install
`./docker.sh install`

i get the following error:
`Step 4/8 : COPY src/package.json src/package-lock.json src/package.json src/webpack.mix.js ./
ERROR: Service 'frontend' failed to build: COPY failed: file not found in build context or excluded by .dockerignore: stat src/package.json: file does not exist
then i stopped install (otherwise later the install will not go on)
^Z
[1]+  Stopped                 ./docker.sh install
`

May be some1 can help why the error happens?
![51542754531_4f4eb471ba_c](https://user-images.githubusercontent.com/67836615/135727270-cfe7bf03-e47a-4e30-8673-5cf99bcce527.jpg)

**Comment by kREATUr67** [comment]
i close the issue, forgot to setup src folder 1st. was not aware of this way.

**Comment by vpnost** [comment]
> i close the issue, forgot to setup src folder 1st. was not aware of this way.

Got the same issue, how did you setup src folder ?

**Comment by kREATUr67** [comment]
at the end this script didn't work, i think it was too old and so long unfortunately not updated by the author, so i installed in normal way
